language: node_js
node_js:
- '6.0'
branches:
  only:
  - master
script:
- npm run build

deploy:
  provider: firebase
  token:
    secure: evRKHs4pOE3Mn9MUGMhC7pZf0ENJMM0HHyfLv1ktvwCyjSPEUPGe2IEvrbirgkQFT95tSAGOmc3M6ruUBhwKndBTBKXnOIMSfsczcS9ycZO6Dm5cmRsDjdQj1bxBmpRrGK1VJKYNq5cRpWYiTBGP88BWzbf0DGue2dgXVEnJWtqRKr1AZT9L/OLkgsTlLlu938f9rxYTo95eZGwF8EelBdqdFJscX/9UF47wR5KZw9mSlz5el46IE5otFqxxg2U2h4Z+Xk1Q3rlPNTmiol/2/LL3O8KWNK8WpkOaiYiObrbHgX6+BG9lB1/WdRxEc3UmCI80w2WGWotluPkGMAKQFLO1t2LEjjYxRxKvPZHwN/Yuym5UCV7zLivetcrpeE0JUd6xBXe5paWpcSNj3eR8aK6yzqas3vY+wdsxbUpJZEwkXdSuXLkn4RH3ilqDNBHv0gKshBQ9LLmJitwU9UtiJjThSGlmcdA7ZnOHW4HPimukmWPVe0ZKBgF+OqkCvEvtSJRDvg6Pg/aRA/TEqUezv8ZwqqcztB4aAKfL1HXQaGJXzaczHG/O/lsefv+1+UG7Tf0g/OGepiOb80e5mhNsyzyeeRs6eKBsfc6XFwHDwyxp6uq1f3MuzpcjhxhcRNXW+RAq/92swh/z4YdQo7RzsgFAWAmgbxTIDZMvuNCyYT4=
